version: "3.8"

name: tig-stack

services:
  # InfluxDB Instance
  influxdb:
    image: influxdb:2.7.1
    hostname: influxdb
    ports:
      - "8086:8086"
    env_file:
      - ./env/influxdb.env
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-etc-data:/etc/influxdb2

  # Telegraf Standalone Instance
  telegraf:
    image: telegraf:1.27.4
    hostname: telegraf
    volumes:
      - ./config/telegraf-standalone.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb

  # ActiveMQ Instance
  activemq:
    image: rmohr/activemq:5.15.9
    hostname: activemq
    ports:
      - "8161:8161"
      - "1883:1883"
    volumes:
      - activemq-data:/var/lib/activemq/data

  # Telegraf MQTT Listener Instance
  telegraf-mqtt-consummer:
    image: telegraf:1.27.4
    hostname: telegraf-mqtt-consummer
    volumes:
      - ./config/telegraf-mqtt-consummer.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - activemq
      - influxdb

  # Custom Simple MQTT Publisher
  mqtt-publisher:
    image: tig-mqtt-publisher
    build:
      context: ./mqtt-publisher
      no_cache: true
      tags:
        - tig-mqtt-publisher
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    depends_on:
      - activemq

  # Grafana instance
  grafana:
    image: grafana/grafana:10.0.0
    hostname: grafana
    ports:
      - "8080:3000"
    env_file:
      - ./env/grafana.env
    volumes:
      - ./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
      - ./dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  # InfluxDB local storage
  influxdb-data:
    external: false
  influxdb-etc-data:
    external: false
  # ActiveMQ local storage
  activemq-data:
    external: false
  # MQTT Publisher local storage
  mosquitto-data:
    external: false
  mosquitto-log:
    external: false
  # Grafana local storage
  grafana-data:
    external: false
